version: '3.8'

services:
  traefik:
    image: traefik:v3.0
    container_name: traefik
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80" # Entrypoint 80 uniquement
    ports:
      - "80:80"       # Port de test pour la pipeline
      - "8081:8081"   # Interface Web de Traefik (Optionnel)
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - web

  apache-test:
    image: httpd:latest
    container_name: apache-server
    ports:
      - "8080:80"     # Apache répond directement sur le port 8080 de la VM !
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.apache.entrypoints=web"
      - "traefik.http.routers.apache.rule=PathPrefix(`/`)"
      - "traefik.http.services.apache.loadbalancer.server.port=80"
    networks:
      - web

networks:
  web:
    external: false
